import {
  Atom,
  Bot,
  BrainCircuit,
  ChartSpline,
  CircleDot,
  Columns3,
  Crosshair,
  Dices,
  Dna,
  Funnel,
  Gamepad2,
  Gauge,
  GitFork,
  Grid3x3,
  Layers3,
  Lightbulb,
  MessagesSquare,
  Mountain,
  Network,
  Orbit,
  Puzzle,
  Repeat,
  Route,
  Scale,
  ScanEye,
  Shapes,
  Sigma,
  Sparkles,
  Spline,
  Target,
  Trees,
  TrendingUp,
  Waves,
  Workflow,
  type LucideIcon,
} from 'lucide-react'

const GLYPHS: Record<string, LucideIcon> = {
  'ai/introduction': Sparkles,
  'ai/intelligent-agents': Bot,
  'ai/uninformed-search': Network,
  'ai/informed-search': Route,
  'ai/adversarial-search': Gamepad2,
  'ai/local-search': Mountain,
  'ai/genetic-algorithms': Dna,
  'ai/csp': Puzzle,
  'ai/knowledge-logic': Lightbulb,
  'ai/probabilistic-reasoning': Dices,
  'ai/mdp': Grid3x3,
  'ai/reinforcement-learning': Target,
  'ai/nlp-basics': MessagesSquare,
  'ai/transformers-attention': ScanEye,
  'ai/llms-generative-ai': BrainCircuit,
  'ai/ai-ethics': Scale,
  'ml/introduction': Workflow,
  'ml/data-preprocessing': Funnel,
  'ml/linear-regression': TrendingUp,
  'ml/gradient-descent': Waves,
  'ml/bias-variance': Spline,
  'ml/regularization': Sigma,
  'ml/logistic-regression': ChartSpline,
  'ml/knn': Crosshair,
  'ml/naive-bayes': Dices,
  'ml/decision-trees': GitFork,
  'ml/ensemble-methods': Trees,
  'ml/svm': Shapes,
  'ml/k-means': CircleDot,
  'ml/dbscan-hierarchical': Orbit,
  'ml/pca': Layers3,
  'ml/perceptron': Atom,
  'ml/neural-networks': BrainCircuit,
  'ml/backpropagation': Repeat,
  'ml/cnn': ScanEye,
  'ml/evaluation-metrics': Gauge,
  'ml/cross-validation': Columns3,
}

export function TopicGlyph({ topicKey, size = 18, className }: { topicKey: string; size?: number; className?: string }) {
  const Icon = GLYPHS[topicKey] ?? Sparkles
  return <Icon size={size} className={className} aria-hidden="true" />
}
